---
name: Audacious
dotfiles:
- ".config/audacious/config"
- ".config/audacious/plugin-registry"
- ".config/audacious/playlists"
- ".config/audacious/playlist-state"
- ".config/audacious/scrobbler.log"
