---
name: Factorio
dotfiles:
- Library/Application Support/factorio/config
- Library/Application Support/factorio/mods
- Library/Application Support/factorio/saves
- Library/Application Support/factorio/player-data.json
