---
name: Adobe Lightroom
dotfiles:
- Library/Application Support/Adobe/Lightroom
- Library/Preferences/com.adobe.Lightroom4.plist
- Library/Preferences/com.adobe.Lightroom5.plist
- Library/Preferences/com.adobe.Lightroom6.plist
