---
name: Light Table
dotfiles:
- Library/Application Support/LightTable/plugins
- Library/Application Support/LightTable/settings
- Library/Application Support/LightTable/User
- Library/Preferences/com.kodowa.LightTable.plist
