---
name: Messages
dotfiles:
- Library/Preferences/com.apple.iChat.AIM.plist
- Library/Preferences/com.apple.iChat.Jabber.plist
- Library/Preferences/com.apple.iChat.StatusMessages.plist
- Library/Preferences/com.apple.iChat.Yahoo.plist
