dotfiles:
  - Library/Application Support/Code/User/snippets
  - Library/Application Support/Code/User/keybindings.json
  - Library/Application Support/Code/User/settings.json
  - .config/Code/User/snippets
  - .config/Code/User/keybindings.json
  - .config/Code/User/settings.json
